### ISSUE TITLE
Lap Kstone

### ISSUE THREAD

**Issue by sonbm7112** [bmson7112/TTS-VTNet#18]

**Comment by sonbm7112** [comment]
# Thực hiện cài đặt và thử nghiệm Kstone trên cumh k8s tạo bởi Kind 
- Hưỡng dẫn cài đặt trên minikube, kubeadm, tke đã có sẵn tại https://github.com/kstone-io/kstone/tree/master/docs/installation

## 1.  Tạo cụm k8s, lưu ý, nên sử dụng  kindest/node  ở các phiên bản cũ, **tránh dùng phiên bản mới nhất** để tránh gặp phải lỗi không đáng có
- Tạo file `kind-config.yaml` có nội dung như sau:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
```
- Dùng lệnh `kind create cluster --config kind-config.yaml --image kindest/node:v1.22.0` để tạo cụm ta được kết quả
![image](https://github.com/bmson7112/TTS-VTNet/assets/79183573/3f21e7b5-3156-46e3-b758-3b9e1b3f9d3b)
- Triển khai `ingress controller` thông qua các lệnh:
```sh
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
```
```sh
kubectl wait --namespace ingress-nginx \
  --for=condition=ready pod \
  --selector=app.kubernetes.io/component=controller \
  --timeout=90s
```
- KIểm tra ingress controller chạy chưa:
![image](https://github.com/bmson7112/TTS-VTNet/assets/79183573/d1209c79-d515-4157-b83a-c2ce1b283a8f)

## 2. Triển khai Kstone
### 2.1. Sửa đổi cấu hình Helm
- Cài đặt Helm theo hướng dẫn tại https://helm.sh/docs/intro/install/
- Clone Helm repo của Kstone 
```
git clone -b release-0.2 https://github.com/kstone-io/kstone.git
cd kstone
cd ./charts
`
- Tạo Admin token  để có thể truy cập bằng dashboard-api
```sh
kubectl create serviceaccount kube-admin -n kube-system
kubectl create clusterrolebinding kube-admin --clusterrole=cluster-admin --serviceaccount=kube-system:kube-admin
```
- Lấy Admin token từ cụm Kind
```sh
kubectl get secrets -o jsonpath="{.items[?(@.metadata.annotations['kubernetes\.io/service-account\.name']=='kube-admin')].data.token}" -n kube-system|base64 --decode
```
- Kết quả trả về :
![image](https://github.com/bmson7112/TTS-VTNet/assets/79183573/bee33f42-2d64-4729-8ebd-8b5b50d44331)
- Truy cập vào file `values.yaml` theo đường dẫn  `charts/charts/dashboard-api/values.yaml` và điền token mới lấy được vào phần `  token: ${token}` như hình:
![image](https://github.com/bmson7112/TTS-VTNet/assets/79183573/dd3830b8-2c58-434a-a0e3-9e54e1a70cc4)
- Truy cập vào file `charts/charts/kube-prometheus-stack/values.yaml` sử đổi các giá trị `prometheusOperator:
  enabled: true` thành `prometheusOperator:
  enabled: false` và `prometheus:
  enabled: true` thành `prometheus:
  enabled: false`

### 2.2 Cài đặt
- Tạo Kstone namespace
```sh
kubectl create ns kstone
```
- Cài đặt Helm cho môi trường test : 
```sh
cd charts/
helm install kstone . -n kstone -f values.test.yaml
```
![image](https://github.com/bmson7112/TTS-VTNet/assets/79183573/e4c496c5-fa74-480f-bd24-cbe974ffc8b7)
- Tạo Ingress Rule
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kstone-ingress
  namespace: kstone
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kstone-dashboard
                port:
                  number: 80
          - path: /apis
            pathType: Prefix
            backend:
              service:
                name: kstone-dashboard-api
                port:
                  number: 80
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: kstone-grafana
                port:
                  number: 80
EOF
```
- Expose Ingress Port
```sh
kubectl port-forward deployment/ingress-nginx-controller 8080:80 --namespace ingress-nginx --address 0.0.0.0
```
- Sau đó truy cập vào `localhost:8080` , username mặc định là `admin`, mật khẩu là `adm1n@kstone.io`. Sau khi đổi mật khẩu ta có giao diện của Kstone như hình dưới
![image](https://github.com/bmson7112/TTS-VTNet/assets/79183573/d5178eaf-060e-488b-bffa-616aad3b3429)
- Giao diện thêm etcd cluster
![image](https://github.com/bmson7112/TTS-VTNet/assets/79183573/53b471f7-ab1d-4cab-9dea-e2d8b8a0074a)
- Giao diện Monitor
![image](https://github.com/bmson7112/TTS-VTNet/assets/79183573/4768ef98-be20-4fad-8fb1-1284730beffe)
